---
title: "ARIMA"
author: "Scott Girten"
date: "October 16, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Get Notes on Differencing

## ARIMA (p,1,q)

**AR**

$Y_t - Y_{t-1} = \phi_1(Y{t-1} - Y_{t-2}) + \phi_2(Y_{t-2} - Y_{t-3} + ... + \phi_p(Y_{t-p} - Y_{t-p-1}) + e_t - \theta_1e_{t-1} - \theta_2e_{t-2} - ... - \theta_qe_{t-q}$

Check book for how to simplify, the end result is (p. 94?)

**Difference Notation**

Characteristic Polynomial:

$1 - (1 + \phi_1)x - (\phi_2 - \phi_1)x^2 - ... - (\phi_p - \phi_{p-1})$

factors into

$(1 - \phi_1x - \phi_2x^2 - ... - \phi_px^p)(1 - x)$

This process looks like an AR process, but the root of $1 - x = 0$ where $x = 1$.  


### IMA(1,1)

Think of it as a weighted average of a white noise process

$Y_t - Y_{t-1} = e_t - \theta_1 e_{t-1}$

$Y_t = Y_{t-1} + e_t - \theta e_{t-1}$

$Y_t = e_t + (1 - \theta)e_{t-1} + \theta)e_{t-2} + \theta)e_{t-3} + ... -\theta e_{-m-1}$

### IMA(2,2)

$Y_t - Y_{t-2} = e_t - \theta_1 e_{t-1} - \theta_2 e_{t-2}$

### ARI(1,1)

$Y_t - Y_{t-1} = \phi (Y_{t-1} - Y_{t-2}) + e_t$

$Y_t = (1+phi)Y_{t-1} - \phi Y_{t-2} + e_t$

## General ARIMA

$(1 - \phi_1x - \phi_2x^2 - ... - \phi_px^p)(1-x)^d(1 + \psi_1x \psi_2x^2 + ...)$

Page 96 - Equating powers to solve for $\psi_i$ weights.

General formula: $\psi_k = (1+\theta)\psi_{k-1} - \theta\psi_{k-2}$ where $\psi_o = 1$

or

$\psi_k = \frac{1 - \theta^{k+1}}{1 - \theta}$

## Autocorrelation Function (ACF)

$Y_1, Y_2, ..., Y_n$

$r = \frac{\sum_{t=k+1}^n (Y_t-\bar{Y})(Y_{t-k}-\bar{Y})}{\sum_{t=1}^n (Y_t-\bar{Y})}$

$r_k$ statistics to approximate $\rho_k$

Copy notes from handout (ACF and PCF Graphs)

Copy notes from handout (Method of Moments Estimators)








